server:
  port: 0

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true



eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
